### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by reyesruiz** [reyesruiz/PizzaDriver#81]
> Task :app:connectedDebugAndroidTest
Starting 2 tests on test(AVD) - 9

com.digitalruiz.pizzadriver.AddOrderNumber > addOrderNumberTest[test(AVD) - 9] FAILED 
	java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.view.menu.ActionMenuItemView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at com.digitalruiz.pizzadriver.MainActivity.onCreate(MainActivity.java:53)

[InstrumentationResultParser]: Ignoring repeated failed event for com.digitalruiz.pizzadriver.AddOrderNumber#addOrderNumberTest. Stack: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.digitalruiz.pizzadriver/com.digitalruiz.pizzadriver.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.view.menu.ActionMenuItemView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.view.menu.ActionMenuItemView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
at com.digitalruiz.pizzadriver.MainActivity.onCreate(MainActivity.java:53)
at android.app.Activity.performCreate(Activity.java:7136)
at android.app.Activity.performCreate(Activity.java:7127)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:730)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
... 11 more

> Task :app:connectedDebugAndroidTest FAILED
Tests on test(AVD) - 9 failed: Instrumentation run failed due to 'Process crashed.'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///Users/runner/work/PizzaDriver/PizzaDriver/app/build/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 23s
53 actionable tasks: 53 executed
Error: The process '/bin/sh' failed with exit code 1
/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
OK: killing emulator, bye bye
OK
INFO    | Discarding the changed state: command-line flag
WARNING | Discarding the changed state (command-line flag).

**Comment by reyesruiz** [comment]
Nothing to do.
